[env:bluepill]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink

lib_deps =
  jcw/JeeH@^7.1.0

extra_scripts =
  pre:../mount_wasm3.py

build_flags =
  -Dd_m3FixedHeap=8192
  -Dd_m3CodePageAlignSize=512
  -Dd_m3EnableValidation=0
  -Dd_m3HasFloat=0
  -Dd_m3HasRefTypes=0
  -Os -Wfatal-errors
