; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200

extra_scripts =
  pre:../mount_wasm3.py

[env:mkr1000]
platform = atmelsam
board = mkr1000USB

build_flags =
  -O3 -Wfatal-errors
  #-flto
  #-fPIC -fomit-frame-pointer -foptimize-sibling-calls

[env:due]
platform = atmelsam
board = due

build_flags =
  -O3 -Wfatal-errors
  -flto

[env:mega1284]
platform = atmelavr
board = wildfirev3

build_flags =
  -Dd_m3CodePageAlignSize=512
  -Dd_m3EnableValidation=0
  -Dd_m3HasFloat=0
  -Dd_m3HasRefTypes=0
  -Os -Wfatal-errors
  -flto

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 460800

board_build.f_cpu = 160000000L

build_flags =
  -Dd_m3FixedHeap=8192
  -O3 -Wfatal-errors
  #-flto
  #-fPIC -fverbose-asm -save-temps=obj

[env:esp32]
; Arduino v3.3.11 / IDF v5.5.5
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip

board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
  -DLED_BUILTIN=13
  -Dd_m3FixedHeap=8192
  -O3 -Wfatal-errors

[env:tinyBLE]
platform = nordicnrf51
board = seeedTinyBLE

build_flags =
  -O3 -Wfatal-errors

[env:blenano]
platform = nordicnrf51
board = redBearLabBLENano

build_flags =
  -O3 -Wfatal-errors

[env:blenano2]
platform = nordicnrf52
board = redbear_blenano2

build_flags =
  -O3 -Wfatal-errors

[env:teensy31]
platform = teensy
board = teensy31
upload_protocol = teensy-cli

build_flags =
  -O3 -Wfatal-errors
  -flto

[env:bluepill-mapple]
platform = ststm32
board = bluepill_f103c8_128k
board_build.core = maple
upload_protocol = stlink
#upload_protocol = dfu

# the maple core's gcc 7.2 segfaults linking the library with -flto
build_flags =
  -Dd_m3FixedHeap=8192
  -Dd_m3EnableValidation=0
  -Dd_m3HasFloat=0
  -Dd_m3HasRefTypes=0
  -Os -Wfatal-errors

[env:bluepill]
platform = ststm32
board = bluepill_f103c8
upload_protocol = stlink

build_flags =
  -Dd_m3FixedHeap=8192
  -Dd_m3EnableValidation=0
  -Dd_m3HasFloat=0
  -Dd_m3HasRefTypes=0
  -Os -Wfatal-errors
  -flto

[env:az3166]
platform = ststm32
board = mxchip_az3166

build_flags =
  -O3 -Wfatal-errors
  -flto

[env:maix]
platform = kendryte210
board = sipeed-maix-one-dock

build_flags =
  -O3 -Wfatal-errors

[env:titiva]
platform = titiva
board = lptm4c1294ncpdt

build_flags =
  -DLED_BUILTIN=13
  -O3 -Wfatal-errors
