typedef uint32_t M3Result;

enum M3ResultCode {
    m3Err_none = 0,
    // general errors
    m3Err_mallocFailed,
    
    // parse errors
    m3Err_incompatibleWasmVersion,
    m3Err_wasmMalformed,
    m3Err_misorderedWasmSection,
    m3Err_wasmUnderrun,
    m3Err_wasmOverrun,
    m3Err_wasmMissingInitExpr,
    m3Err_lebOverflow,
    m3Err_missingUTF8,
    m3Err_wasmSectionUnderrun,
    m3Err_wasmSectionOverrun,
    m3Err_invalidTypeId,
    m3Err_tooManyMemorySections,
    m3Err_malformedElementSection,
    m3Err_unknownTypeSigIndex,
    m3Err_typeListOverflow,
    // link errors
    m3Err_moduleAlreadyLinked,
    m3Err_functionLookupFailed,
    m3Err_functionImportMissing,
    m3Err_functionIndexOutOfBounds,
    m3Err_functionSignatureMissingReturnType,
    m3Err_functionSignatureTooManyReturnTypes,
    m3Err_noStartFunction,
    m3Err_startFunctionIndexOutOfBounds,
    m3Err_argCountOverflow,
    m3Err_unknownArgumentType,
    m3Err_argumentCountMismatch,
    m3Err_dataSegmentOverflow,
    m3Err_tableOverflow,
    m3Err_nonZeroMVPTableIndex,
    m3Err_unknownReturnType,
    // compilation errors
    m3Err_noCompiler,
    m3Err_unknownOpcode,
    m3Err_functionStackOverflow,
    m3Err_functionStackUnderrun,
    m3Err_mallocFailedCodePage,
    m3Err_settingImmutableGlobal,
    m3Err_optimizerFailed,
    m3Err_slotUsageOverflow,
    m3Err_invalidBlockDepth,
    m3Err_localIndexOutOfBounds,
    m3Err_functionTypeIndexOutOfBounds,
    m3Err_noOperationForOpCode,
    m3Err_unexpectedBlockStackOffset,
    // runtime errors
    m3Err_missingCompiledCode,
    m3Err_wasmMemoryOverflow,
    m3Err_globalMemoryNotAllocated,
    m3Err_globaIndexOutOfBounds,
    m3Err_noModulesLoaded,
    m3Err_unallocatedLinearMemory,
    // traps
    m3Err_trapOutOfBoundsMemoryAccess,
    m3Err_trapDivisionByZero,
    m3Err_trapIntegerOverflow,
    m3Err_trapIntegerConversion,
    m3Err_trapIndirectCallTypeMismatch,
    m3Err_trapTableIndexOutOfRange,
    m3Err_trapExit,
    m3Err_trapAbort,
    m3Err_trapUnreachable,
    m3Err_trapStackOverflow,
    m3Err_trapNullTableElement,
};


static const char *const errorToStringMap[] = {
    [m3Err_none] = "none",
    // general errors
    [m3Err_mallocFailed] = "memory allocation failed",
    
    // parse errors
    [m3Err_incompatibleWasmVersion] = "incompatible Wasm binary version",
    [m3Err_wasmMalformed]           = "malformed Wasm binary",
    [m3Err_misorderedWasmSection]   = "out of order Wasm section",
    [m3Err_wasmUnderrun]            = "underrun while parsing Wasm binary",
    [m3Err_wasmOverrun]             = "overrun while parsing Wasm binary",
    [m3Err_wasmMissingInitExpr]     = "missing init_expr in Wasm binary",
    [m3Err_lebOverflow]             = "LEB encoded value overflow",
    [m3Err_missingUTF8]             = "invalid length UTF-8 string",
    [m3Err_wasmSectionUnderrun]     = "section underrun while parsing Wasm binary",
    [m3Err_wasmSectionOverrun]      = "section overrun while parsing Wasm binary",
    [m3Err_invalidTypeId]           = "unknown value_type",
    [m3Err_tooManyMemorySections]   = "Wasm MVP can only define one memory per module",
    [m3Err_malformedElementSection] = "error parsing Element section",
    [m3Err_unknownTypeSigIndex]     = "unknown type sig index",
    [m3Err_typeListOverflow]        = "type list count exceeds 32 types",
    // link errors
    [m3Err_moduleAlreadyLinked]                 = "attempting to bind module to multiple runtimes",
    [m3Err_functionLookupFailed]                = "function lookup failed",
    [m3Err_functionImportMissing]               = "missing imported function",
    [m3Err_functionIndexOutOfBounds]            = "function index out of range",
    [m3Err_functionSignatureMissingReturnType]  = "malformed function signature; missing return type",
    [m3Err_functionSignatureTooManyReturnTypes] = "malformed function signature; too many return types",
    [m3Err_noStartFunction]                     = "start function not found",
    [m3Err_startFunctionIndexOutOfBounds]       = "start function index out of bounds",
    [m3Err_argCountOverflow]                    = "arg count overflow",
    [m3Err_unknownArgumentType]                 = "unknown argument type",
    [m3Err_argumentCountMismatch]               = "arguments count mismatch",
    [m3Err_dataSegmentOverflow]                 = "data segment overflowing linear memory",
    [m3Err_tableOverflow]                       = "table overflow",
    [m3Err_nonZeroMVPTableIndex]                = "element table index must be zero for MVP",
    [m3Err_unknownReturnType]                   = "unknown return type",
    // compilation errors
    [m3Err_noCompiler]                   = "no compiler found for opcode",
    [m3Err_unknownOpcode]                = "unknown opcode",
    [m3Err_functionStackOverflow]        = "compiling function overrun its stack height limit",
    [m3Err_functionStackUnderrun]        = "compiling function underran the stack",
    [m3Err_mallocFailedCodePage]         = "memory allocation failed when acquiring a new M3 code page",
    [m3Err_settingImmutableGlobal]       = "attempting to set an immutable global",
    [m3Err_optimizerFailed]              = "optimizer failed", // not a fatal error. a result
    [m3Err_slotUsageOverflow]            = "slot usage count overflow",
    [m3Err_invalidBlockDepth]            = "invalid block depth",
    [m3Err_localIndexOutOfBounds]        = "local index out of bounds",
    [m3Err_functionTypeIndexOutOfBounds] = "function type index out of range",
    [m3Err_noOperationForOpCode]         = "no operation found for opcode",
    [m3Err_unexpectedBlockStackOffset]   = "unexpected block stack offset",
    // runtime errors
    [m3Err_missingCompiledCode]      = "function is missing compiled m3 code",
    [m3Err_wasmMemoryOverflow]       = "runtime ran out of memory",
    [m3Err_globalMemoryNotAllocated] = "global memory is missing from a module",
    [m3Err_globaIndexOutOfBounds]    = "global index is too large",
    [m3Err_noModulesLoaded]          = "no modules loaded",
    [m3Err_unallocatedLinearMemory]  = "unallocated linear memory",
    // traps
    [m3Err_trapOutOfBoundsMemoryAccess]  = "[trap] out of bounds memory access",
    [m3Err_trapDivisionByZero]           = "[trap] integer divide by zero",
    [m3Err_trapIntegerOverflow]          = "[trap] integer overflow",
    [m3Err_trapIntegerConversion]        = "[trap] invalid conversion to integer",
    [m3Err_trapIndirectCallTypeMismatch] = "[trap] indirect call type mismatch",
    [m3Err_trapTableIndexOutOfRange]     = "[trap] undefined element",
    [m3Err_trapExit]                     = "[trap] program called exit",
    [m3Err_trapAbort]                    = "[trap] program called abort",
    [m3Err_trapUnreachable]              = "[trap] unreachable executed",
    [m3Err_trapStackOverflow]            = "[trap] stack overflow",
    [m3Err_trapNullTableElement]         = "trap: table element is null"
};