name: publish

on:
  push:
    tags:
      - "v*.*.*"

env:
  draft: true

jobs:
  windows:
    runs-on: windows-latest
    name: ${{ matrix.config.target }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        config:
        - {target: wasm3-win-x64,         platform: "-A x64",     toolset: "-T ClangCL"   }
        - {target: wasm3-win-x86,         platform: "-A Win32",   toolset: "-T ClangCL"   }
        - {target: wasm3-strace-win-x64,  platform: "-A x64",     toolset: "-T ClangCL",  cflags: "-DDEBUG -Dd_m3EnableStrace=2 -Dd_m3RecordBacktraces=1" }

    env:
      LDFLAGS: -s

    steps:
    - uses: actions/checkout@v7

    - name: Configure
      env:
        CFLAGS: ${{ matrix.config.cflags }}
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.config.platform }} ${{ matrix.config.toolset }} ..

    - name: Build
      run: |
        cmake --build build --config Release
        cp ./build/Release/wasm3.exe ./${{ matrix.config.target }}.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.config.target }}
        path: ./${{ matrix.config.target }}.exe
        if-no-files-found: error

  linux-x64:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7

    - name: Setup musl
      run: |
        sudo apt update
        sudo apt install musl-tools

        # Add musl-gcc include paths
        sudo cp -a /usr/include/linux /usr/include/x86_64-linux-musl/
        sudo cp -a /usr/include/asm-generic /usr/include/x86_64-linux-musl/
        sudo cp -a /usr/include/x86_64-linux-gnu/asm /usr/include/x86_64-linux-musl/

    - name: Configure, Build wasm3
      env:
        CC: musl-gcc
        LDFLAGS: "-static -s"
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        cp ./wasm3 ../wasm3-linux-x64.elf

    - name: Configure, Build wasm3-strace
      env:
        CC: musl-gcc
        LDFLAGS: "-static -s"
        CFLAGS: -DDEBUG -Dd_m3EnableStrace=2 -Dd_m3RecordBacktraces=1
      run: |
        mkdir build-strace
        cd build-strace
        cmake ..
        cmake --build .
        cp ./wasm3 ../wasm3-strace-linux-x64.elf

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: wasm3-linux-x64
        path: |
          ./wasm3-linux-x64.elf
          ./wasm3-strace-linux-x64.elf
        if-no-files-found: error

  linux-cross:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v7

    - name: Build for all targets
      run: |
        python3 build-cross.py --notest --nowasi
        cd build-cross
        tar -czvf ../wasm3-linux-other.tar.gz wasm3-linux-*

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: wasm3-linux-other
        path: wasm3-linux-other.tar.gz

  cosmopolitan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7

    - name: Build αcτµαlly pδrταblε εxεcµταblε
      run: |
        cd platforms/cosmopolitan
        ./build.sh
        cp ./wasm3.com ../../wasm3-cosmopolitan.com
        cp ./wasm3.com.dbg ../../wasm3-cosmopolitan.com.dbg

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: wasm3-cosmopolitan
        path: |
          ./wasm3-cosmopolitan.com
          ./wasm3-cosmopolitan.com.dbg
        if-no-files-found: error

  wasi:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7
    - name: Setup environment
      env:
        WASI_VERSION: 11
        WASI_VERSION_FULL: "11.0"
      run: |
        echo "WASI_VERSION=${WASI_VERSION}" >> $GITHUB_ENV
        echo "WASI_VERSION_FULL=${WASI_VERSION_FULL}" >> $GITHUB_ENV
        echo "WASI_SDK_PATH=${GITHUB_WORKSPACE}/.toolchains/wasi-sdk-${WASI_VERSION_FULL}" >> $GITHUB_ENV
    - name: Install WASI SDK
      run: |
        mkdir -p .toolchains
        cd .toolchains
        WASI_TAR=wasi-sdk-${WASI_VERSION_FULL}-linux.tar.gz
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_VERSION}/${WASI_TAR}
        tar xvf ${WASI_TAR}

    - name: Configure, Build wasm3
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE="${WASI_SDK_PATH}/share/cmake/wasi-sdk.cmake" -DWASI_SDK_PREFIX="${WASI_SDK_PATH}" ..
        cmake --build .
        cp ./wasm3.wasm ../wasm3-wasi.wasm

    - name: Configure, Build wasm3-strace
      env:
        CFLAGS: -DDEBUG -Dd_m3EnableStrace=2 -Dd_m3RecordBacktraces=1
      run: |
        mkdir build-strace
        cd build-strace
        cmake -DCMAKE_TOOLCHAIN_FILE="${WASI_SDK_PATH}/share/cmake/wasi-sdk.cmake" -DWASI_SDK_PREFIX="${WASI_SDK_PATH}" ..
        cmake --build .
        cp ./wasm3.wasm ../wasm3-strace.wasm

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: wasm3-wasi
        path: |
          ./wasm3-wasi.wasm
          ./wasm3-strace.wasm
        if-no-files-found: error

  android:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 11

      - name: Build
        run: |
          cd platforms/android
          ./gradlew build

      - name: Copy
        run: |
          cp ./platforms/android/app/build/outputs/apk/debug/app-debug.apk ./wasm3-android-coremark.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: wasm3-android-coremark
          path: ./wasm3-android-coremark.apk
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs:
      - windows
      - linux-x64
      - linux-cross
      - cosmopolitan
      - wasi
      - android

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: dist
          merge-multiple: true

      - name: List artifacts
        run: |
          find dist -type f -maxdepth 2 -print

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          draft: ${{ env.draft }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
